#!/usr/bin/env node
/*
 * vk-to-rust.js
 *
 * Converts a snarkjs Groth16 `verification_key.json` (BN254 / bn128) into a
 * Rust source file exposing `pub const VERIFYINGKEY: Groth16Verifyingkey`
 * laid out exactly as the `groth16-solana` crate (v0.2.0) expects.
 *
 * Layout / conventions targeted (groth16-solana 0.2.0 — light-protocol):
 *   pub struct Groth16Verifyingkey<'a> {
 *       pub nr_pubinputs: usize,
 *       pub vk_alpha_g1:  [u8; 64],          // G1: x(32) || y(32)
 *       pub vk_beta_g2:   [u8; 128],         // G2: x.c1 || x.c0 || y.c1 || y.c0
 *       pub vk_gamme_g2:  [u8; 128],         // (sic) misspelled in the crate
 *       pub vk_delta_g2:  [u8; 128],
 *       pub vk_ic:        &'a [[u8; 64]],    // one G1 point per public input + 1
 *   }
 *
 * Each field element is encoded as 32 big-endian bytes.
 * G2 coordinates use the imaginary part FIRST, then the real part
 * (arkworks / light-protocol ordering); snarkjs stores [real, imag] so we swap.
 *
 * Usage:
 *   node program/scripts/vk-to-rust.js circuits/build/verification_key.json \
 *     > program/programs/proven-kyc/src/verifying_key.rs
 */

const fs = require("fs");

const path = process.argv[2];
if (!path) {
  console.error("usage: node vk-to-rust.js <verification_key.json>");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(path, "utf8"));

// Decimal field element -> 32 big-endian bytes.
function toBytes(dec) {
  const h = BigInt(dec).toString(16).padStart(64, "0");
  if (h.length > 64) {
    throw new Error(`field element does not fit in 32 bytes: ${dec}`);
  }
  const out = [];
  for (let i = 0; i < 64; i += 2) out.push(parseInt(h.slice(i, i + 2), 16));
  return out;
}

// BN254 base field prime.
const FIELD_P =
  21888242871839275222246405745257275088696311157297823662689037894645226208583n;

// Modular inverse (extended Euclid) for projective -> affine conversion.
function modInv(a, m) {
  let [old_r, r] = [((a % m) + m) % m, m];
  let [old_s, s] = [1n, 0n];
  while (r !== 0n) {
    const q = old_r / r;
    [old_r, r] = [r, old_r - q * r];
    [old_s, s] = [s, old_s - q * s];
  }
  return ((old_s % m) + m) % m;
}

// G1 point -> affine x(32) || y(32). snarkjs stores projective [x, y, z].
// The on-chain alt_bn128 syscalls expect AFFINE coordinates, with the point at
// infinity (z == 0) encoded as (0, 0) — NOT the raw projective (x, y). An
// insecure/dummy trusted setup can yield infinity IC points ([0,1,0]); encoding
// those as (0,1) is off-curve and makes alt_bn128_multiplication fail
// (PreparingInputsG1MulFailed). Normalise z here so any valid VK works.
const g1 = (p) => {
  const x = BigInt(p[0]);
  const y = BigInt(p[1]);
  const z = p[2] !== undefined ? BigInt(p[2]) : 1n;
  if (z === 0n) {
    // Point at infinity -> 64 zero bytes (alt_bn128 affine encoding of identity).
    return new Array(64).fill(0);
  }
  if (z === 1n) {
    return [...toBytes(x), ...toBytes(y)];
  }
  const zInv = modInv(z, FIELD_P);
  const ax = (x * zInv) % FIELD_P;
  const ay = (y * zInv) % FIELD_P;
  return [...toBytes(ax), ...toBytes(ay)];
};

// G2 affine point. snarkjs stores [[x.c0, x.c1], [y.c0, y.c1], [1, 0]] (real, imag).
// groth16-solana wants imaginary first then real: x.c1 || x.c0 || y.c1 || y.c0.
const g2 = (p) => [
  ...toBytes(p[0][1]),
  ...toBytes(p[0][0]),
  ...toBytes(p[1][1]),
  ...toBytes(p[1][0]),
];

const arr = (xs) => `[${xs.join(", ")}]`;

const ic = vk.IC.map((p) => `\t\t${arr(g1(p))},`).join("\n");

const out = `// @generated by program/scripts/vk-to-rust.js — DO NOT EDIT BY HAND.
// Source: circuits/build/verification_key.json (snarkjs Groth16, BN254).
// Public inputs (${vk.nPublic}): Ax, Ay, currentDateInt, currentYY, minAge, nullifierHash.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
\tnr_pubinputs: ${vk.IC.length - 1},
\tvk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
\tvk_beta_g2: ${arr(g2(vk.vk_beta_2))},
\tvk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
\tvk_delta_g2: ${arr(g2(vk.vk_delta_2))},
\tvk_ic: &[
${ic}
\t],
};
`;

process.stdout.write(out);
