#!/usr/bin/env node
/*
 * vk-to-rust.js
 *
 * Converts a snarkjs Groth16 `verification_key.json` (BN254 / bn128) into a
 * Rust source file exposing `pub const VERIFYINGKEY: Groth16Verifyingkey`
 * laid out exactly as the `groth16-solana` crate (v0.2.0) expects.
 *
 * Layout / conventions targeted (groth16-solana 0.2.0 — light-protocol):
 *   pub struct Groth16Verifyingkey<'a> {
 *       pub nr_pubinputs: usize,
 *       pub vk_alpha_g1:  [u8; 64],          // G1: x(32) || y(32)
 *       pub vk_beta_g2:   [u8; 128],         // G2: x.c1 || x.c0 || y.c1 || y.c0
 *       pub vk_gamme_g2:  [u8; 128],         // (sic) misspelled in the crate
 *       pub vk_delta_g2:  [u8; 128],
 *       pub vk_ic:        &'a [[u8; 64]],    // one G1 point per public input + 1
 *   }
 *
 * Each field element is encoded as 32 big-endian bytes.
 * G2 coordinates use the imaginary part FIRST, then the real part
 * (arkworks / light-protocol ordering); snarkjs stores [real, imag] so we swap.
 *
 * Usage:
 *   node program/scripts/vk-to-rust.js circuits/build/verification_key.json \
 *     > program/programs/proven-kyc/src/verifying_key.rs
 */

const fs = require("fs");

const path = process.argv[2];
if (!path) {
  console.error("usage: node vk-to-rust.js <verification_key.json>");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(path, "utf8"));

// Decimal field element -> 32 big-endian bytes.
function toBytes(dec) {
  const h = BigInt(dec).toString(16).padStart(64, "0");
  if (h.length > 64) {
    throw new Error(`field element does not fit in 32 bytes: ${dec}`);
  }
  const out = [];
  for (let i = 0; i < 64; i += 2) out.push(parseInt(h.slice(i, i + 2), 16));
  return out;
}

// G1 affine point: x(32) || y(32). snarkjs stores [x, y, z=1]; we drop z.
const g1 = (p) => [...toBytes(p[0]), ...toBytes(p[1])];

// G2 affine point. snarkjs stores [[x.c0, x.c1], [y.c0, y.c1], [1, 0]] (real, imag).
// groth16-solana wants imaginary first then real: x.c1 || x.c0 || y.c1 || y.c0.
const g2 = (p) => [
  ...toBytes(p[0][1]),
  ...toBytes(p[0][0]),
  ...toBytes(p[1][1]),
  ...toBytes(p[1][0]),
];

const arr = (xs) => `[${xs.join(", ")}]`;

const ic = vk.IC.map((p) => `\t\t${arr(g1(p))},`).join("\n");

const out = `// @generated by program/scripts/vk-to-rust.js — DO NOT EDIT BY HAND.
// Source: circuits/build/verification_key.json (snarkjs Groth16, BN254).
// Public inputs (${vk.nPublic}): Ax, Ay, currentDateInt, currentYY, minAge, nullifierHash.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
\tnr_pubinputs: ${vk.IC.length - 1},
\tvk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
\tvk_beta_g2: ${arr(g2(vk.vk_beta_2))},
\tvk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
\tvk_delta_g2: ${arr(g2(vk.vk_delta_2))},
\tvk_ic: &[
${ic}
\t],
};
`;

process.stdout.write(out);
